- .codeclimate.yml
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/changelog-configuration.json
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .gitignore
- .goreleaser.yml
- Makefile
- Makefile.vars.mk
- README.md
- go.mod
First steps in setting up CI/CD parts
Note: This PR doesn't do enough to make checks pass, resp. some Checks only work later on when adding some boilerplate code
> Setup up CI/CD

- Dockerfile
- Makefile
- apis/organization/v1/organization_types.go
- apiserver/organization/organization.go
- config/deployment/apiservice.yaml
- config/deployment/deployment.yaml
- config/deployment/kustomization.yaml
- config/deployment/service.yaml
- config/namespace/kustomization.yaml
- config/namespace/namespace.yaml
- config/rbac/kustomization.yaml
- config/rbac/role.yaml
- config/rbac/role_binding.yaml
- config/rbac/role_binding_auth_delegator.yaml
- config/rbac/service_account.yaml
- local-env/setup-kind.sh
This PR updates the RBAC rules and introduces a sample deployment that is used for the local dev enviroment and as a base for the commodore component.
> Add control-API sample deployment

- Makefile
- config/rbac/role.yaml
- config/rbac/role_binding.yaml
As suggested in https://github.com/appuio/component-control-api/pull/6
> Make API server ClusterRole name more unique

- config/crd/apiextensions.k8s.io/v1/kustomization.yaml
> Add new CRDs to released crd.yml assets

- config/user-rbac/organization-admin-role.yml
It's not explicitly stated in the design doc, but organization admins almost definitely need to edit rolebindings
> Give organization admins the option to manage RoleBindings

- apis/organization/v1/organization_types.go
> Add Organization to scheme

- config/crd/apiextensions.k8s.io/v1/kustomization.yaml
Add `Team` CRD when running kustomize.
> Add teams CRD when running kustomize

- apiserver/organization/rolebindings.go
- config/rbac/role.yaml
- config/user-rbac/organization-admin-role.yml
> Give API server permission to create RoleBindings for teams

- controllers/user_controller.go
> Reconcile on owned objects

- config/rbac/controller/role.yaml
- config/user-rbac/organization-admin-role.yml
- controllers/organization_members_controller.go
* Give controller permission to create and delete OrgMember resources
* Prevent org-admins from creating more OrgMember resources
...
> Adjust OrgMember permissions

- controller.go
> Correctly bind zap flags to controller Cobra command

- .gitignore
- Makefile
- go.mod
- go.sum
- local-env/kind.mk
- local-env/setup-kind.sh
- tools.go
* Add `sigs.k8s.io/kind` to `tools.go` (Fixes #20)
* Add logic to setup admission webhooks on local env
> Add logic to setup admission webhooks in local test environment

- Makefile
- README.md
- local-env/kind.mk
> Add instructions to register locally running controller with kind local environment in README

- local-env/README.md
add note about openSSL in the readme, see https://github.com/appuio/control-api/pull/59
> add note about openssl

- .goreleaser.yml
- Makefile.vars.mk
- README.md
- local-env/setup-kind.sh
- Improved `local-dev` descriptions from my setup experience.
- Adds MacOS support.
- Uses up-to-date K8s version.
- Adds ARM64 build/docker image
> `local-dev` improvements 

- apiserver/billing/billing.go
- apiserver/billing/odoostorage/create.go
- apiserver/billing/odoostorage/get.go
- apiserver/billing/odoostorage/list.go
- apiserver/billing/odoostorage/odoostorage.go
- apiserver/billing/odoostorage/update.go
- apiserver/billing/rbac.go
- apiserver/billing/rbac_test.go
> Properly expose storage methods through createRBACWrapper

- apiserver/billing/odoostorage/odoo/odoo8/client/client.go
> Close http.Body when requesting a new session

- apiserver/billing/odoostorage/odoo/odoo8/odoo8.go
- apiserver/billing/odoostorage/odoo/odoo8/odoo8_test.go
> Move accounting contact name to annotation

- controller.go
- controllers/org_billing_ref_link_metric.go
- controllers/org_billing_ref_link_metric_test.go
> Expose link between organization and billing-entity as a Prometheus metric

- go.mod
> Go mod tidy with 1.20

- controllers/invitation_redeem_controller.go
This fixes a reconciliation loop in the invitation redeem controller, which would otherwise re-trigger a reconciliation by unconditionally updating a redeemed invitation's status object.
...
> Fix reconciliation loop in redeem controller

- apis/user/v1/invitation_types.go
> Add `omitempty` to Invitation `status.conditions` and `status.targetStatuses`

- config/examples/billing-entity.yaml
- config/examples/zone.yaml
- local-env/README.md
* Adds more details to how BE are used on local-env
* Adds a Zone example
> Add Billing instructions to local-env readme and zone example

- apiserver/authwrapper/storage.go
Seems to be only sometimes in request info. Would need more debugging to find out what exactly is included in the request info and what not.
> Pass request verb correctly

- apiserver/user/invitation_storage.go
> Fix storage layer order to expose `redeem` methods

- local-env/README.md
- local-env/templates/invitation-token.tpl
Shortcut to get invitation links by running `kubectl get invitations -o go-template-file=local-env/templates/invitation-token.tpl`
> Update local-env readme with go-template example

- controllers/invitation_redeem_controller.go
- controllers/invitation_redeem_controller_rolename_test.go
- controllers/invitation_redeem_controller_test.go
> Allow redeemer of an invitation to access (read) it

- apiserver/billing/rbac.go
- apiserver/billing/rbac_test.go
- config/rbac/apiserver/role.yaml
- config/user-rbac/basic-user-role.yml
> Add permission to create BE; give admin permission over created BE

- api.go
- apiserver/billing/odoostorage/odoo/odoo8/odoo8.go
- apiserver/billing/odoostorage/odoo/odoo8/odoo8_test.go
- apiserver/billing/odoostorage/odoostorage.go
> Allow configuring static BE fields

- controllers/org_info_metric.go
- controllers/org_info_metric_test.go
> Remove billing entity information from `appuio_control_organization_info` metric

- controllers/sale_order_controller_test.go
> Add more tests for sales order controller

- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
> Remove explicit go mod cache. `actions/setup-go` does it already.
