apiserver/organization/delete.go, apiserver/organization/delete_test.go
Return a valid organization object to prevent missleading errors when deleting organizations
...
=> Fix return value when deleting Organizations

apiserver/organization/members.go, apiserver/organization/rolebindings.go, config/rbac/role.yaml
=> Add missing RBAC permissions to the apiserver role

config/deployment/deployment.yaml, config/user-rbac/basic-user-role.yml, config/user-rbac/basic-user-rolebinding.yml, config/user-rbac/kustomization.yaml, config/user-rbac/organization-admin-role.yml, config/user-rbac/organization-viewer-role.yml, local-env/setup-kind.sh, local-env/templates/kind-oidc.yaml.tpl
With this PR for the local environment we 
* Allow any authenticated user to view Zones and create organizations as well es manage created organizations
* Switch to `preferred_username` claim from the email
=> Add user RBAC to default config

apiserver/organization/create.go, apiserver/organization/create_test.go, apiserver/organization/mock/namespace.go, apiserver/organization/namespace.go
By linking them with an ownerRef, a controller can easily reconcile on both without jumping through some hoops.
=> Link OrganizationMembers to Organization with an owner reference

config/deployment/deployment.yaml
* Increase memory limit and request. While memory usage was not higher  during testing, increasing this can lead to better performance on a larger cluster, because caching
* Allow CPU to spike for lower latency
* Switch to pull policy always. This lead to some issues when using tag latest
=> Increase default resource request/limit for API server

apis/v1/organizationmembers_type.go, apis/v1/user_types.go, apiserver/organization/create.go, apiserver/organization/create_test.go, config/crd/apiextensions.k8s.io/v1/base/appuio.io_organizationmembers.yaml, config/crd/apiextensions.k8s.io/v1/base/appuio.io_users.yaml
We decided to transition to only using the username and not the ID. It's the adapters job to resolve the username if necessary
Change documented in: https://github.com/appuio/appuio-io-docs/pull/107
=> Remove user id from reference

config/user-rbac/basic-user-role.yml, config/user-rbac/organization-admin-role.yml
Discovered while reviewing https://github.com/appuio/cloud-portal/pull/86. Worked fine with `kubectl` as that uses `patch`
=> Switch user roles from imaginary `edit` to actual `update` verb

apiserver/organization/create.go, apiserver/organization/create_test.go, apiserver/organization/mock/rolebindings.go, apiserver/organization/organization.go, apiserver/organization/rolebindings.go, apiserver/organization/rolebindings_test.go
This prevents for example service account to unexpectedly be added as members
=> Only add APPUiO user as members on Organization creation

Makefile, config/rbac/controller/role.yaml, controller.go, controllers/organization_members_controller.go, controllers/organization_members_controller_test.go
This PR introduces a new flag that allows us to specify clusterroles that will be assigned to every organization member for their namespace
(I also sneakily removed the generated code from code coverage because I found the reported number depressingly low. It's a bit hacky, not sure if we should do that :see_no_evil:)
=> Add option to bind ClusterRoles to all organization members

config/webhook/kustomization.yaml, config/webhook/kustomizeconfig.yaml, config/webhook/manifests.yaml, config/webhook/service.yaml, controller.go, webhooks/user_webhook.go, webhooks/user_webhook_test.go
We use the "low-level" approach of registering our handler directly on the controller manager's webhook server as we are able to access the manager's Kubernetes client with that approach.
The client is not easily accessible when taking the "high-level" approach of implementing the `Validator` interface on the type which we want to validate.
Note that the service name and namespace in the `ValidatingWebhookConfiguration` generated by controller-gen are not configurable and need to adjusted during deployment.
...
=> Implement validating admission webhook for CR users.appuio.io

controller.go
We need to be able to control the location of the controller webhook server certificate directory. See https://github.com/kubernetes-sigs/controller-runtime/blob/eb292e5d9bd6c59663fc6777ae2b99f901f386e4/pkg/manager/manager.go#L219-L224
=> Expose controller webhook server certificate directory configuration

controller.go
Allow configuring the port on which the webhook server listens.
=> Add controller command line flag to specify the webhook server port

webhooks/user_webhook.go, webhooks/user_webhook_test.go
We should not deny Users without a default org. This currently denies our user import.
=> Allow User resources with no default organization

apiserver/billing/rbac.go, config/rbac/apiserver/role.yaml
Fixes permissions so the apiserver can create clusterroles and bindings.
=> Fix APIServer permissions

api.go, apiserver/organization/billingentity_validate.go, apiserver/organization/create.go, apiserver/organization/create_test.go, apiserver/organization/organization.go, apiserver/organization/organization_test.go, apiserver/organization/update.go, apiserver/organization/update_test.go, config/rbac/apiserver/role.yaml
Uses impersonation to check if a user can get a billing entity when referencing it in an Organization.
=> `Organization.spec.billingEntityRef` validation

config/deployment/controller/deployment.yaml, config/deployment/controller/kustomization.yaml, config/deployment/controller/metrics-service.yaml
Add service referencing the controller metrics port.
=> Expose controller metrics

config/user-rbac/basic-user-role.yml
Fixes listing billing entities/invitations for users that are allowed to `get` billing entities/invitations.
BEs/Inviations are filtered further by `get` for `list`, and `watch` in the aggregate API server.
Allows authenticated users to redeem invitations. They are guarded by token.
=> Fix list permission on BillingEntity/Invitation (+ redeem)

config/rbac/controller/role.yaml, controller.go, controllers/invitation_cleanup_controller.go, controllers/invitation_cleanup_controller_test.go
Adds a new controller which takes care of removing invites that are expired, or have been redeemed for a certain amount of time (default 30 days).
...
=> Remove expired and redeemed invites

README.md, config/webhook/manifests.yaml, controllers/invitation_redeem_controller.go, controllers/targetref/targetref.go, controllers/targetref/targetref_test.go, local-env/setup-kind.sh, webhooks/invitation_webhook.go, webhooks/invitation_webhook_test.go, webhooks/user_webhook_test.go
A user creating or updating an Invitation must be referenced in the object he is trying to create an invitation for.
Only direct user memberships are tested since there is not yet a concept for groups in the control API.
=> Validate invitation targetRefs to prevent privilege escalation

apiserver/user/invitation_redeem.go
`invitations/INV/TOKEN` becomes `invitations/INV?token=TOKEN`
This fixes RBAC where the token was seen as a sub-resource.
=> Switch passing invitation token from path to url.Values

config/user-rbac/basic-user-role.yml
Allow empty verb to allow upstream server to pass custom verbs to our aggregated API server. All permissions are double checked by the API server and our aggregate API server.
=> Fix basic users permission to redeem invitations

Makefile, apiserver/billing/odoostorage/odoo/odoo8/client/debug.go, controllers/invitation_cleanup_controller.go, controllers/invitation_redeem_controller.go, controllers/invitation_token_controller.go, controllers/org_billingentity_name_cache_controller.go, controllers/organization_members_controller.go, controllers/user_controller.go, webhooks/invitation_webhook.go, webhooks/user_webhook.go
This sets all log statements to use log level 1, which corresponds to `debug` level.
Additionally, the makefile now starts the controller with debug log level, because I figured debug logs would be useful for local dev.
...
=> Adjust logger log level to match debug level

apiserver/user/invitation_storage.go, apiserver/user/rbac.go, apiserver/user/rbac_test.go, config/rbac/apiserver/role.yaml
This PR makes the creator of an invitation the owner of it. It allows the user to edit and delete invitations they created.
This was forgotten when implementing https://github.com/appuio/control-api/pull/98.
=> Make the creator of an Invitation the owner

controller.go, controllers/invitation_email_controller.go, controllers/invitation_email_controller_test.go, mailsenders/mail_senders.go, mailsenders/renderer.go, mailsenders/renderer_test.go
Renders email bodies inside the controller using Go templates because:
- Mailgun logs are broken with mailgun templates since [2019](https://feedback.mailgun.com/forums/156243-feature-requests/suggestions/38608327-fix-quick-view-for-templates).
- We might want to add SMTP at some point.
- We might need to pass additional data like links to the portal.
- We expect to only ever send plaintext emails anyways.
=> Render email body in controller

controller.go, controllers/invitation_redeem_controller.go, controllers/targetref/targetref.go, controllers/targetref/targetref_test.go, webhooks/invitation_webhook.go
We use the prefix only for RBAC objects. Everything in our own API-Server is non-prefixed 🤷‍♀️
=> Invitation: Remove `appuio#` prefix from non RBAC objects

controller.go, controllers/invitation_email_controller.go, controllers/invitation_email_controller_test.go, controllers/invitation_email_pending_metric.go, controllers/invitation_email_pending_metric_test.go
Adds the following new metrics to the controller:
```
HELP control_api_invitation_emails_pending_current Amount of e-mails that have not been sent yet
control_api_invitation_emails_pending_current 0
control_api_invitation_emails_sent_failed_total 0
control_api_invitation_emails_sent_success_total 0
```
These metrics allow to observe and alert on the status of invitation e-mail sending.
...
=> Add metrics that indicate the status of email sending

config/user-rbac/basic-user-role.yml
Otherwise `kubectl` shows permission error without passing `--validate=false` for basic users.
=> Allow kubectl to validate CRDs client side

config/rbac/controller/role.yaml, controllers/billingentity_email_cronjob.go
Due to copy-paste error, the annotations were giving the wrong permissions, causing things to not work.
...
=> Fix service account kubebuilder annotations

config/user-rbac/basic-user-role.yml, pkg/sar/resource_attributes.go, pkg/sar/sar.go, webhooks/invitation_webhook.go, webhooks/invitation_webhook_test.go, webhooks/user_webhook.go, webhooks/user_webhook_test.go
Allows users to create their own settings by validating the name of the created settings. This allows users to set settings before they are reconciled from the external IDP.
Having a special permission `create rbac.appuio.io/users` allows overriding the validation for controllers creating users.
=> Allow users to create their own settings

local-env/templates/realm.json.tpl
Recent Keycloak versions don't support custom mappers in individual clients anymore.
To work around this issue, we instead patch the default `roles` client scope to include the `local-dev` client roles in the `groups` field of the ID and access tokens.
...
=> Update Keycloak Realm template for local environment setup

apis/organization/v1/organization_types.go, controllers/org_info_metric.go, controllers/org_info_metric_test.go, controllers/sale_order_controller.go, controllers/sale_order_controller_test.go, controllers/saleorder/saleorder_storage.go, controllers/saleorder/saleorder_storage_test.go
=> Fix naming of `salesOrder` properties in status subresource

apiserver/billing/rbac.go, config/rbac/controller/role.yaml, controller.go, controllers/billingentity_email_cronjob.go, controllers/billingentity_email_cronjob_test.go, controllers/billingentity_rbac_cronjob.go, controllers/billingentity_rbac_cronjob_test.go, controllers/common_test.go, pkg/billingrbac/billingrbac.go
Used a cron job since we never implemented watch for BEs.
Some basteling to allow for SSAing the roles.
=> Implement BillingEntity RBAC reconcile

api.go, apiserver/organization/billingentity_validate.go, apiserver/organization/organization.go
Required for migration when we switch off the BE part of the API-Server.
=> Allow organization BE ref validation to be skipped.

controller.go, controllers/default_organization_controller.go, controllers/default_organization_controller_test.go
We want to add the usability feature "As a new user, I want my default organization to be set automatically when I create my first organization or accept an invitation, so that I can get started right away and don't have to worry about setup."
We simplify this to "every user who is in exactly 1 organization and does not have a default configured should have their default organization set to the one organization they are a member of". This will automatically solve the use case above both for creating your first org and for accepting your first invite.
...
=> Add default organization to users that are in exactly one organization

apiserver/billing/odoostorage/odoo/odoo16/odoo16.go
`list` already loads correct partner
=> Odoo 16 Storage: Fix loading wrong partner in `get`

apiserver/billing/odoostorage/odoo/odoo16/odoo16.go
This should fix BE creation in Odoo 16.
=> Remove categary id linking to old Odoo 8 "roleaccount"

apiserver/billing/odoostorage/odoo/odoo16/odoo16.go, apiserver/billing/odoostorage/odoo/odoo16/odoo16_test.go, apiserver/billing/odoostorage/odoo/odoo16/odoo16mock/odoo16.go
The Odoo client uses http.Client under the hood which should be reused since it keeps connections open.
The initialization of the Odoo client is not thread-safe so I added a wrapper that fully initializes the client before any parallelized call. See comments on `FullInitialization()`.
=> Fix memory leak by reusing Odoo client
